name: getBranchName
on: [push]
jobs:
  which_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Extract branch name
        if: github.event_name != 'pull_request'
        shell: bash
        run: echo "::set-env name=BRANCH_NAME::$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: Get branch name
        run: echo 'The branch name is' $BRANCH_NAME
